version: "3"
services:
  database:
    container_name: postgresdb
    restart: always
    image: postgres:latest
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=database
  app:
    build: ./source
    container_name: stats_app
    restart: always
    ports: ["5000:5000"]
    volumes: ['./source:/app']
    stdin_open: true
    tty: true
    depends_on:
      - database
#    networks:
#      - backend

#networks:
#  backend: